# Generated by Django 4.0.2 on 2022-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'PHONE'), (2, 'FACEBOOK'), (3, 'EMAIL'), (4, 'INSTAGRAM'), (5, 'WHATSAPP'), (6, 'TIKTOK'), (7, 'YOUTUBE'), (8, 'TELEGRAM')], null=True),
        ),
    ]
